### PR TITLE
Bug/999 fix release build

### LINKED ISSUE #999: fix Release build
RelWithDebInfo fails in skaled repo

### PR DESCRIPTION
**Pull request by olehnikolaiev**
fixes #999 

resolve build issue by moving to cxx-20 and fixing false-positive error from gcc-11

### CODE REVIEW

**Review by PropzSaladaz — APPROVED** [review]

File: bite/BiteCodec.cpp [hunk 1]
```diff
@@ -84,8 +84,7 @@ std::vector<uint8_t> BiteCodec::encodeCTXData(
 
     auto finalData = allArgs.encode();
 
-    std::vector<uint8_t> data;
-    data.reserve(BITE2_FUNCTION_SELECTOR_SIZE_BYTES + finalData.size());
+    std::vector<uint8_t> data(BITE2_FUNCTION_SELECTOR_SIZE_BYTES + finalData.size());
```
Comment (PropzSaladaz) [inline bite/BiteCodec.cpp:87]: default constructor default initializes with N items. when we insert using .end() it will insert at index N, not index 0 as before.

`.reserve()` preserved 0 items in the vector, thus `.end()` returned the start of the vector

**Review by PropzSaladaz — APPROVED** [review]

**Review by PropzSaladaz — APPROVED** [review]

**Review by kladkogex — APPROVED** [review]
